/* Catálogo: 30 peças tiradas dos posts do @giselebeatrizacessorios (dez/2025 a set/2026).
   Nome e descrição vêm da legenda do post; preço, da legenda ou do valor escrito na própria foto.
   Fotos: o código do post (e -n para a foto n do carrossel), na ordem em que aparecem na ficha.

   pecas:  o que dá para pedir. Num conjunto, a cliente marca as peças que quer.
   opcoes: peça com variações (cor, modelo da foto). A escolhida vai na mensagem.
   preco null = "Consultar valor". */

export const categorias = [
  { id: 'colares', nome: 'Colares' },
  { id: 'brincos', nome: 'Brincos' },
  { id: 'aneis', nome: 'Anéis' },
  { id: 'pulseiras', nome: 'Pulseiras' },
  { id: 'conjuntos', nome: 'Conjuntos' },
  { id: 'prata', nome: 'Prata 925' },
]

export const produtos = [
  {
    id: 'colar-olho-de-tigre',
    nome: 'Colar olho de tigre com pérola barroca',
    desc: 'Pedras olho de tigre com pérola barroca natural.',
    cats: ['colares'],
    pecas: [{ nome: 'Colar', preco: 249.9 }],
    fotos: ['DdcMsqNpnzd'],
    post: 'DdcMsqNpnzd',
    data: '2026-09-18',
  },
  {
    id: 'morganita-e-topazio',
    nome: 'Morganita e topázio com pérola barroca',
    desc: 'Cristais morganita e topázio com pérola barroca natural.',
    cats: ['conjuntos', 'colares', 'brincos', 'aneis'],
    pecas: [
      { nome: 'Brinco longo', preco: 219.9 },
      { nome: 'Brinco segundo furo', preco: 109.9 },
      { nome: 'Colar', preco: 329.9 },
      { nome: 'Anel', preco: 109.9 },
    ],
    fotos: ['DdbkVVeIECz-4', 'DdbkVVeIECz', 'DdbkVVeIECz-3', 'DdbkVVeIECz-5', 'DdbkVVeIECz-2'],
    post: 'DdbkVVeIECz',
    data: '2026-09-18',
  },
  {
    id: 'conjunto-canelado',
    nome: 'Conjunto canelado dourado',
    desc: 'O detalhe faz toda a diferença: peças lisas e exuberantes.',
    cats: ['conjuntos', 'aneis', 'brincos', 'colares'],
    pecas: [
      { nome: 'Anel dedinho', preco: 139.9 },
      { nome: 'Brinco', preco: 129.9 },
      { nome: 'Colar', preco: 159.9 },
    ],
    fotos: ['DdUUjwTCSZR', 'DdUUjwTCSZR-2', 'DdUUjwTCSZR-3', 'DdUUjwTCSZR-4'],
    post: 'DdUUjwTCSZR',
    data: '2026-09-15',
  },
  {
    id: 'colar-elefante',
    nome: 'Colar longo de elefante',
    desc: 'Longo, com 60 cm, e pedras roalita rubi e turquesa.',
    cats: ['colares'],
    pecas: [{ nome: 'Colar', preco: 419.9 }],
    fotos: ['DdUJRQ7IGbO-2', 'DdUJRQ7IGbO', 'DdUJRQ7IGbO-3', 'DdUJRQ7IGbO-4'],
    post: 'DdUJRQ7IGbO',
    data: '2026-09-15',
  },
  {
    id: 'conjunto-gota-banho-de-ouro',
    nome: 'Conjunto gota no banho de ouro',
    desc: 'Brinco, colar e anel no banho de ouro, cravejados.',
    cats: ['conjuntos', 'brincos', 'colares', 'aneis'],
    pecas: [
      { nome: 'Brinco', preco: 109.9 },
      { nome: 'Colar', preco: 109.9 },
      { nome: 'Anel', preco: 109.9 },
    ],
    fotos: ['DdUIHpkIFkV-5', 'DdUIHpkIFkV', 'DdUIHpkIFkV-2', 'DdUIHpkIFkV-3', 'DdUIHpkIFkV-4'],
    post: 'DdUIHpkIFkV',
    data: '2026-09-15',
  },
  {
    id: 'conjunto-onix',
    nome: 'Conjunto ródio branco com ônix',
    desc: 'Ródio branco com zircônias ônix.',
    cats: ['conjuntos', 'brincos', 'colares', 'aneis'],
    pecas: [
      { nome: 'Brinco', preco: 109.9 },
      { nome: 'Colar', preco: 109.9 },
      { nome: 'Anel', preco: 109.9 },
    ],
    fotos: ['DdUH3DsIJP3-4', 'DdUH3DsIJP3', 'DdUH3DsIJP3-2', 'DdUH3DsIJP3-3'],
    post: 'DdUH3DsIJP3',
    data: '2026-09-15',
  },
  {
    id: 'conjunto-tres-banhos',
    nome: 'Conjunto três banhos',
    desc: 'Trio de brincos, colar e trio de anéis em três banhos.',
    cats: ['conjuntos', 'brincos', 'colares', 'aneis'],
    pecas: [
      { nome: 'Trio de brincos', preco: 219.9 },
      { nome: 'Colar', preco: 179.9 },
      { nome: 'Trio de anéis', preco: 209.9 },
    ],
    fotos: ['DdRtb8uCfSz-2', 'DdRtb8uCfSz', 'DdRtb8uCfSz-3', 'DdRtb8uCfSz-4'],
    post: 'DdRtb8uCfSz',
    data: '2026-09-14',
  },
  {
    id: 'elos-dois-banhos',
    nome: 'Elos em dois banhos',
    desc: 'Corrente e pulseira de elos em dois banhos, e a pulseira só dourada.',
    cats: ['colares', 'pulseiras'],
    pecas: [
      { nome: 'Corrente dois banhos', preco: 359.9 },
      { nome: 'Pulseira dois banhos', preco: 179.9 },
      { nome: 'Pulseira dourada', preco: 159.9 },
    ],
    fotos: [
      'DdRtFGeibZy-7',
      'DdRtFGeibZy',
      'DdRtFGeibZy-2',
      'DdRtFGeibZy-3',
      'DdRtFGeibZy-4',
      'DdRtFGeibZy-5',
      'DdRtFGeibZy-6',
      'DdRtFGeibZy-8',
    ],
    post: 'DdRtFGeibZy',
    data: '2026-09-14',
  },
  {
    id: 'colar-chave',
    nome: 'Colar longo com chave',
    desc: 'Colar de 70 cm com mais 10 cm de extensor.',
    cats: ['colares'],
    pecas: [{ nome: 'Colar', preco: 309.9 }],
    fotos: ['DdRstoNCepK-3', 'DdRstoNCepK', 'DdRstoNCepK-2'],
    post: 'DdRstoNCepK',
    data: '2026-09-14',
  },
  {
    id: 'colar-perolas-naturais',
    nome: 'Colar de pérolas naturais',
    desc: 'Pérolas naturais em fios de nylon, 45 cm com mais 5 cm de extensor.',
    cats: ['colares'],
    pecas: [{ nome: 'Colar', preco: 219.9 }],
    fotos: ['DdRsbuvCTub', 'DdRsbuvCTub-2', 'DdRsbuvCTub-3'],
    post: 'DdRsbuvCTub',
    data: '2026-09-14',
  },
  {
    id: 'sunstone-e-jasper',
    nome: 'Sunstone e jasper imperial',
    desc: 'Pedras sunstone, jasper imperial oval e cristal aqua marine.',
    cats: ['conjuntos', 'brincos', 'colares', 'pulseiras'],
    pecas: [
      { nome: 'Brinco', preco: 269.9 },
      { nome: 'Colar', preco: 489.9 },
      { nome: 'Pulseira', preco: 359.9 },
    ],
    fotos: ['Dcyq-PzIPFA-3', 'Dcyq-PzIPFA-2', 'Dcyq-PzIPFA', 'Dcyq-PzIPFA-4', 'Dcyq-PzIPFA-5', 'Dcyq-PzIPFA-6'],
    post: 'Dcyq-PzIPFA',
    data: '2026-09-02',
  },
  {
    id: 'turquesa-e-olho-de-tigre',
    nome: 'Turquesa e olho de tigre',
    desc: 'Pedras naturais com cristal rosa: turquesa, olho de tigre e turmalina rosa.',
    cats: ['conjuntos', 'brincos', 'colares', 'pulseiras'],
    pecas: [
      { nome: 'Brinco', preco: 219.9 },
      { nome: 'Colar', preco: 419.9 },
      { nome: 'Pulseira', preco: 339.9 },
    ],
    fotos: [
      'DcypzNfoP3u-6',
      'DcypzNfoP3u',
      'DcypzNfoP3u-2',
      'DcypzNfoP3u-3',
      'DcypzNfoP3u-4',
      'DcypzNfoP3u-5',
      'DcypzNfoP3u-7',
      'DcypzNfoP3u-8',
    ],
    post: 'DcypzNfoP3u',
    data: '2026-09-02',
  },
  {
    id: 'perolas-classicas',
    nome: 'Pérolas clássicas',
    desc: 'Pérolas são clássicas e atemporais. Brinco e colar.',
    cats: ['conjuntos', 'brincos', 'colares'],
    pecas: [
      { nome: 'Brinco', preco: 99.9 },
      { nome: 'Colar', preco: 89.9 },
    ],
    fotos: ['Db51kqJKwnM'],
    post: 'Db51kqJKwnM',
    data: '2026-08-11',
  },
  {
    id: 'classico-e-elegante',
    nome: 'Conjunto clássico e elegante',
    desc: 'Bracelete e o conjunto de anel e brinco.',
    cats: ['conjuntos', 'pulseiras', 'aneis', 'brincos'],
    pecas: [
      { nome: 'Bracelete', preco: 179.9 },
      { nome: 'Conjunto anel e brinco', preco: 139.9 },
    ],
    fotos: ['Db51aSslgO1', 'Db51aSslgO1-2', 'Db51aSslgO1-3'],
    post: 'Db51aSslgO1',
    data: '2026-08-11',
  },
  {
    id: 'brinco-perola-oval',
    nome: 'Brinco pérola oval',
    desc: 'Argola dourada com pérola oval.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 159.9 }],
    fotos: ['DZ-ACWClih4'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-laco-madreperola',
    nome: 'Brinco laço meia madrepérola',
    desc: 'Laço meia madrepérola com filetes de zircônias.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 209.9 }],
    fotos: ['DZ-ACWClih4-3'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-gota-cravejada',
    nome: 'Brinco gota cravejada',
    desc: 'Gota dourada toda cravejada.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 139.9 }],
    fotos: ['DZ-ACWClih4-4'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-estrela',
    nome: 'Brinco estrela cravejada',
    desc: 'Duas estrelas cravejadas, uma sobre a outra.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 309.9 }],
    fotos: ['DZ-ACWClih4-5'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-elos-ovais',
    nome: 'Brinco elos ovais',
    desc: 'Elos ovais em cascata. Dourado ou prateado.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 169.9 }],
    opcoes: { nome: 'Cor', lista: ['Dourado', 'Prateado'], porFoto: true },
    fotos: ['DZ-ACWClih4-6', 'DZ-ACWClih4-7'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-rodio-zirconia',
    nome: 'Brinco ródio com zircônia',
    desc: 'No ródio, com pedra quadrada e borda cravejada.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 129.9 }],
    fotos: ['DZ-ACWClih4-8'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-argola-perola',
    nome: 'Brinco argola com pérola',
    desc: 'Argolinha com pérola.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 119.9 }],
    fotos: ['DZ-ACWClih4-13'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'brinco-gota-lisa',
    nome: 'Brinco gota lisa',
    desc: 'Gota grande e lisa, dourada.',
    cats: ['brincos'],
    pecas: [{ nome: 'Brinco', preco: 189.9 }],
    fotos: ['DZ-ACWClih4-9'],
    post: 'DZ-ACWClih4',
    data: '2026-06-24',
  },
  {
    id: 'cristais-coloridos',
    nome: 'Cristais coloridos',
    desc: 'Cristais, muito brilho e luxo. Joias sofisticadas.',
    cats: ['conjuntos', 'brincos', 'colares', 'aneis'],
    pecas: [
      { nome: 'Brinco', preco: 419.9 },
      { nome: 'Colar', preco: 639.9 },
      { nome: 'Anel (aro 17)', preco: 159.9 },
      { nome: 'Colar e brinco gota', preco: 179.9 },
    ],
    fotos: [
      'DYhvc9aFqi7',
      'DYhvc9aFqi7-3',
      'DYhvc9aFqi7-4',
      'DYhvc9aFqi7-5',
      'DYhvc9aFqi7-6',
      'DYhvc9aFqi7-2',
      'DYhvc9aFqi7-7',
      'DYhvc9aFqi7-8',
    ],
    post: 'DYhvc9aFqi7',
    data: '2026-05-19',
  },
  {
    id: 'sofisticados-e-minimalistas',
    nome: 'Sofisticados e minimalistas',
    desc: 'Pulseira, braceletes e anéis com brinco, cravejados e finos.',
    cats: ['conjuntos', 'pulseiras', 'aneis', 'brincos'],
    pecas: [
      { nome: 'Pulseira', preco: 179.9 },
      { nome: 'Anel (aros 17 e 19) e brinco', preco: 139.9 },
      { nome: 'Anel (aros 15, 17 e 19) e brinco', preco: 139.9 },
      { nome: 'Bracelete fino', preco: 179.9 },
      { nome: 'Bracelete largo', preco: 209.9 },
    ],
    fotos: [
      'DYhtlK7lnWZ',
      'DYhtlK7lnWZ-2',
      'DYhtlK7lnWZ-3',
      'DYhtlK7lnWZ-4',
      'DYhtlK7lnWZ-5',
      'DYhtlK7lnWZ-6',
      'DYhtlK7lnWZ-7',
    ],
    post: 'DYhtlK7lnWZ',
    data: '2026-05-19',
  },
  {
    id: 'organicos',
    nome: 'Orgânicos e belíssimos',
    desc: 'Formas orgânicas em dois tons. Brinco, colar e anel.',
    cats: ['conjuntos', 'brincos', 'colares', 'aneis'],
    pecas: [
      { nome: 'Brinco', preco: 179.9 },
      { nome: 'Colar', preco: 289.9 },
      { nome: 'Anel (aro 21)', preco: 159.9 },
    ],
    fotos: ['DYhsEeMFo2t', 'DYhsEeMFo2t-2', 'DYhsEeMFo2t-3', 'DYhsEeMFo2t-4'],
    post: 'DYhsEeMFo2t',
    data: '2026-05-19',
  },
  {
    id: 'escapulario-madreperola',
    nome: 'Escapulário de madrepérola',
    desc: 'Pérolas de água doce e madrepérola. Escapulário e pulseira.',
    cats: ['colares', 'pulseiras'],
    pecas: [
      { nome: 'Escapulário', preco: 469.9 },
      { nome: 'Pulseira', preco: 219.9 },
    ],
    fotos: ['DVrYUh6Ce22', 'DVrYUh6Ce22-2'],
    post: 'DVrYUh6Ce22',
    data: '2026-03-09',
  },
  {
    id: 'trio-coracoes',
    nome: 'Trio de corações',
    desc: 'Corações são os queridinhos por aqui. Anel e uma dupla de brincos.',
    cats: ['conjuntos', 'aneis', 'brincos'],
    pecas: [{ nome: 'Anel e dupla de brincos', preco: 159.9 }],
    fotos: ['DUbJnTuCZts', 'DUbJnTuCZts-2', 'DUbJnTuCZts-3'],
    post: 'DUbJnTuCZts',
    data: '2026-02-06',
  },
  {
    id: 'trevos-e-perola',
    nome: 'Trevos e pérola',
    desc: 'Brinco de pérola, dupla de argola e trevo, dupla de anéis e colar.',
    cats: ['conjuntos', 'brincos', 'aneis', 'colares'],
    pecas: [
      { nome: 'Brinco de pérola', preco: 109.9 },
      { nome: 'Dupla de argola e trevo', preco: 179.9 },
      { nome: 'Dupla de anéis', preco: 249.9 },
      { nome: 'Colar', preco: 139.9 },
    ],
    fotos: ['DUYvrqhCUKR', 'DUYvrqhCUKR-2', 'DUYvrqhCUKR-3', 'DUYvrqhCUKR-4', 'DUYvrqhCUKR-5', 'DUYvrqhCUKR-6'],
    post: 'DUYvrqhCUKR',
    data: '2026-02-05',
  },
  {
    id: 'brincos-prata-925',
    nome: 'Brincos na prata 925',
    desc: 'Dez modelos na prata 925. Escolha pela foto.',
    cats: ['brincos', 'prata'],
    pecas: [{ nome: 'Brinco', preco: null }],
    opcoes: { nome: 'Modelo', porFoto: true },
    fotos: [
      'DVd4demjU72',
      'DVd4demjU72-2',
      'DVd4demjU72-3',
      'DVd4demjU72-4',
      'DVd4demjU72-5',
      'DVd4demjU72-6',
      'DVd4demjU72-7',
      'DVd4demjU72-8',
      'DVd4demjU72-9',
      'DVd4demjU72-10',
    ],
    post: 'DVd4demjU72',
    data: '2026-03-04',
  },
  {
    id: 'colares-prata-925',
    nome: 'Colares na prata 925',
    desc: 'Doze modelos na prata 925. Escolha pela foto.',
    cats: ['colares', 'prata'],
    pecas: [{ nome: 'Colar', preco: null }],
    opcoes: { nome: 'Modelo', porFoto: true },
    fotos: [
      'DVd4W4jDeLu',
      'DVd4W4jDeLu-2',
      'DVd4W4jDeLu-3',
      'DVd4W4jDeLu-4',
      'DVd4W4jDeLu-5',
      'DVd4W4jDeLu-6',
      'DVd4W4jDeLu-7',
      'DVd4W4jDeLu-8',
      'DVd4W4jDeLu-9',
      'DVd4W4jDeLu-10',
      'DVd4W4jDeLu-11',
      'DVd4W4jDeLu-12',
    ],
    post: 'DVd4W4jDeLu',
    data: '2026-03-04',
  },
]
